import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/hooks/useCart";
import BackToTop from "@/components/ui/BackToTop";
import SocialMediaBar from "@/components/ui/SocialMediaBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <CartProvider>
        <Header />
        {children}
        <Footer />
        <BackToTop />
        <SocialMediaBar />
        <Toaster position="top-right" />
      </CartProvider>
    </body>
  </html>
);

export default RootLayout;
